#include "keyboard.h"

char allegro_keycode_to_character(int keycode, bool shift) {
    if (shift) {
        switch (keycode) {
            case ALLEGRO_KEY_A:
                return 'A';
            case ALLEGRO_KEY_B:
                return 'B';
            case ALLEGRO_KEY_C:
                return 'C';
            case ALLEGRO_KEY_D:
                return 'D';
            case ALLEGRO_KEY_E:
                return 'E';
            case ALLEGRO_KEY_F:
                return 'F';
            case ALLEGRO_KEY_G:
                return 'G';
            case ALLEGRO_KEY_H:
                return 'H';
            case ALLEGRO_KEY_I:
                return 'I';
            case ALLEGRO_KEY_J:
                return 'J';
            case ALLEGRO_KEY_K:
                return 'K';
            case ALLEGRO_KEY_L:
                return 'L';
            case ALLEGRO_KEY_M:
                return 'M';
            case ALLEGRO_KEY_N:
                return 'N';
            case ALLEGRO_KEY_O:
                return 'O';
            case ALLEGRO_KEY_P:
                return 'P';
            case ALLEGRO_KEY_Q:
                return 'Q';
            case ALLEGRO_KEY_R:
                return 'R';
            case ALLEGRO_KEY_S:
                return 'S';
            case ALLEGRO_KEY_T:
                return 'T';
            case ALLEGRO_KEY_U:
                return 'U';
            case ALLEGRO_KEY_V:
                return 'V';
            case ALLEGRO_KEY_W:
                return 'W';
            case ALLEGRO_KEY_X:
                return 'X';
            case ALLEGRO_KEY_Y:
                return 'Y';
            case ALLEGRO_KEY_Z:
                return 'Z';
            case ALLEGRO_KEY_0:
                return ')';
            case ALLEGRO_KEY_1:
                return '!';
            case ALLEGRO_KEY_2:
                return '@';
            case ALLEGRO_KEY_3:
                return '#';
            case ALLEGRO_KEY_4:
                return '$';
            case ALLEGRO_KEY_5:
                return '%';
            case ALLEGRO_KEY_6:
                return '^';
            case ALLEGRO_KEY_7:
                return '&';
            case ALLEGRO_KEY_8:
                return '*';
            case ALLEGRO_KEY_9:
                return '(';
            case ALLEGRO_KEY_PAD_0:
                return '0';
            case ALLEGRO_KEY_PAD_1:
                return '1';
            case ALLEGRO_KEY_PAD_2:
                return '2';
            case ALLEGRO_KEY_PAD_3:
                return '3';
            case ALLEGRO_KEY_PAD_4:
                return '4';
            case ALLEGRO_KEY_PAD_5:
                return '5';
            case ALLEGRO_KEY_PAD_6:
                return '6';
            case ALLEGRO_KEY_PAD_7:
                return '7';
            case ALLEGRO_KEY_PAD_8:
                return '8';
            case ALLEGRO_KEY_PAD_9:
                return '9';
            case ALLEGRO_KEY_TILDE:
                return '~';
            case ALLEGRO_KEY_MINUS:
                return '_';
            case ALLEGRO_KEY_EQUALS:
                return '+';
            case ALLEGRO_KEY_TAB:
                return '\t';
            case ALLEGRO_KEY_OPENBRACE:
                return '{';
            case ALLEGRO_KEY_CLOSEBRACE:
                return '}';
            case ALLEGRO_KEY_ENTER:
                return '\n';
            case ALLEGRO_KEY_SEMICOLON:
                return ':';
            case ALLEGRO_KEY_QUOTE:
                return '"';
            case ALLEGRO_KEY_BACKSLASH:
                return '|';
            case ALLEGRO_KEY_BACKSLASH2:
                return '|';
            case ALLEGRO_KEY_COMMA:
                return '<';
            case ALLEGRO_KEY_FULLSTOP:
                return '>';
            case ALLEGRO_KEY_SLASH:
                return '?';
            case ALLEGRO_KEY_SPACE:
                return ' ';
            case ALLEGRO_KEY_PAD_SLASH:
                return '/';
            case ALLEGRO_KEY_PAD_ASTERISK:
                return '*';
            case ALLEGRO_KEY_PAD_MINUS:
                return '-';
            case ALLEGRO_KEY_PAD_PLUS:
                return '+';
            case ALLEGRO_KEY_PAD_ENTER:
                return '\n';
            case ALLEGRO_KEY_PAD_EQUALS:
                return '=';
            case ALLEGRO_KEY_BACKQUOTE:
                return '`';
            case ALLEGRO_KEY_SEMICOLON2:
                return ';';
        }
    } else {
        switch (keycode) {
            case ALLEGRO_KEY_A:
                return 'a';
            case ALLEGRO_KEY_B:
                return 'b';
            case ALLEGRO_KEY_C:
                return 'c';
            case ALLEGRO_KEY_D:
                return 'd';
            case ALLEGRO_KEY_E:
                return 'e';
            case ALLEGRO_KEY_F:
                return 'f';
            case ALLEGRO_KEY_G:
                return 'g';
            case ALLEGRO_KEY_H:
                return 'h';
            case ALLEGRO_KEY_I:
                return 'i';
            case ALLEGRO_KEY_J:
                return 'j';
            case ALLEGRO_KEY_K:
                return 'k';
            case ALLEGRO_KEY_L:
                return 'l';
            case ALLEGRO_KEY_M:
                return 'm';
            case ALLEGRO_KEY_N:
                return 'n';
            case ALLEGRO_KEY_O:
                return 'o';
            case ALLEGRO_KEY_P:
                return 'p';
            case ALLEGRO_KEY_Q:
                return 'q';
            case ALLEGRO_KEY_R:
                return 'r';
            case ALLEGRO_KEY_S:
                return 's';
            case ALLEGRO_KEY_T:
                return 't';
            case ALLEGRO_KEY_U:
                return 'u';
            case ALLEGRO_KEY_V:
                return 'v';
            case ALLEGRO_KEY_W:
                return 'w';
            case ALLEGRO_KEY_X:
                return 'x';
            case ALLEGRO_KEY_Y:
                return 'y';
            case ALLEGRO_KEY_Z:
                return 'z';
            case ALLEGRO_KEY_0:
                return '0';
            case ALLEGRO_KEY_1:
                return '1';
            case ALLEGRO_KEY_2:
                return '2';
            case ALLEGRO_KEY_3:
                return '3';
            case ALLEGRO_KEY_4:
                return '4';
            case ALLEGRO_KEY_5:
                return '5';
            case ALLEGRO_KEY_6:
                return '6';
            case ALLEGRO_KEY_7:
                return '7';
            case ALLEGRO_KEY_8:
                return '8';
            case ALLEGRO_KEY_9:
                return '9';
            case ALLEGRO_KEY_PAD_0:
                return '0';
            case ALLEGRO_KEY_PAD_1:
                return '1';
            case ALLEGRO_KEY_PAD_2:
                return '2';
            case ALLEGRO_KEY_PAD_3:
                return '3';
            case ALLEGRO_KEY_PAD_4:
                return '4';
            case ALLEGRO_KEY_PAD_5:
                return '5';
            case ALLEGRO_KEY_PAD_6:
                return '6';
            case ALLEGRO_KEY_PAD_7:
                return '7';
            case ALLEGRO_KEY_PAD_8:
                return '8';
            case ALLEGRO_KEY_PAD_9:
                return '9';
            case ALLEGRO_KEY_TILDE:
                return '`';
            case ALLEGRO_KEY_MINUS:
                return '-';
            case ALLEGRO_KEY_EQUALS:
                return '=';
            case ALLEGRO_KEY_TAB:
                return '\t';
            case ALLEGRO_KEY_OPENBRACE:
                return '[';
            case ALLEGRO_KEY_CLOSEBRACE:
                return ']';
            case ALLEGRO_KEY_ENTER:
                return '\n';
            case ALLEGRO_KEY_SEMICOLON:
                return ';';
            case ALLEGRO_KEY_QUOTE:
                return '\'';
            case ALLEGRO_KEY_BACKSLASH:
                return '\\';
            case ALLEGRO_KEY_BACKSLASH2:
                return '\\';
            case ALLEGRO_KEY_COMMA:
                return ',';
            case ALLEGRO_KEY_FULLSTOP:
                return '.';
            case ALLEGRO_KEY_SLASH:
                return '/';
            case ALLEGRO_KEY_SPACE:
                return ' ';
            case ALLEGRO_KEY_PAD_SLASH:
                return '/';
            case ALLEGRO_KEY_PAD_ASTERISK:
                return '*';
            case ALLEGRO_KEY_PAD_MINUS:
                return '-';
            case ALLEGRO_KEY_PAD_PLUS:
                return '+';
            case ALLEGRO_KEY_PAD_ENTER:
                return '\n';
            case ALLEGRO_KEY_PAD_EQUALS:
                return '=';
            case ALLEGRO_KEY_BACKQUOTE:
                return '`';
            case ALLEGRO_KEY_SEMICOLON2:
                return ';';
        }
    }
    return '\0';
}
